#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generate the dry-run twin of every CIS extension whose constraint supports one.

An org policy can carry `dry_run_spec` instead of `spec`: Google evaluates the rule,
writes a violation to the audit log for every action it WOULD have blocked, and blocks
nothing. That is how a breaking control is sized against a live organisation before it
is enforced.

The twin must measure exactly the policy that will later be enforced, or the numbers it
produces answer a question nobody asked. So it is DERIVED from the enforcing fragment
rather than written beside it: same constraint, same rules, `spec` renamed to
`dry_run_spec`, and every `claim` dropped — a dry run discharges nothing.

    uv run scripts/build_dry_run_fragments.py            # write the twins
    uv run scripts/build_dry_run_fragments.py --check    # fail if any is stale

`--check` is a smoke gate and a unit test. Editing a source fragment and forgetting its
twin is exactly the drift this exists to make impossible.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXT = ROOT / "presets/cis-extensions"

# The extensions whose constraints support a dry run, with the param that asks for one.
#
# NOT here, each for its own reason, and the convention tolerates that rather than
# pretending otherwise:
#   shielded-vm            compute.requireShieldedVm is legacy and has no dry-run form
#   cmek                   both CMEK constraints are legacy list constraints, same
#   access-approval        no org policy at all — it is an Access Approval settings resource
#   dns-logging            ships ON by default; there is nothing to size before enforcing
#   internet-ssh-rdp       a hierarchical FIREWALL policy, not an org policy; its own
#                          dry-run story is Google's `goto_next`, already how it passes
#                          the private ranges
DRY_RUNNABLE = {
    "api-key-services": "cis_api_key_services_dry_run",
    "block-project-ssh-keys": "cis_block_project_ssh_keys_dry_run",
    "bucket-retention": "cis_bucket_retention_dry_run",
    "cloud-sql": "cis_cloud_sql_hardening_dry_run",
    "cloud-sql-iam-and-deletion-protection": "cis_cloud_sql_iam_and_deletion_protection_dry_run",
    "confidential-computing": "cis_confidential_computing_dry_run",
}

HEADER = """// GENERATED by scripts/build_dry_run_fragments.py from {source} — do not edit.
//
//   use "presets/cis-extensions/{stem}-dry-run.satz" when {param}
//
// The dry-run twin of {source}. Google evaluates every rule below, writes a
// violation to the audit log for each action it WOULD have blocked, and blocks
// nothing — so the organisation's own numbers answer "will this break us?" before
// the control is enforced. Read them in Cloud Logging:
//
//   protoPayload.metadata."@type"="type.googleapis.com/google.cloud.audit.OrgPolicyViolationInfo"
//
// Promote by switching {param} off
// and {enforcing} on. Both on at once is refused:
// the estate would declare the same policy twice, once measuring and once blocking.
//
// This fragment carries NO claim. A dry run discharges no control while it runs, and
// `require` reports the control as unmet, which is the truth.

"""


def derive(src_text: str, stem: str, param: str, source: str) -> str:
    """Rename `spec` to `dry_run_spec`, drop every claim, restate the header."""
    body = src_text
    # Drop the source's leading comment block and its `pack` line: the twin writes
    # its own header and needs its own pack name.
    m = re.search(r'^pack\s+(\S+)\s+version\s+("[^"]+")\s*$', body, re.M)
    if not m:
        raise SystemExit(f'{source}: no `pack <name> version "x"` line')
    pack_name, pack_version = m.group(1), m.group(2)
    body = body[m.end() :]

    # Every claim, to the end of its block. Claims are top-level and brace-balanced.
    body = drop_claims(body)

    body, n = rename_specs(body)
    if n == 0:
        raise SystemExit(f"{source}: no enforcing `spec {{` block to make a dry run of")

    head = HEADER.format(source=source, stem=stem, param=param, enforcing=param.removesuffix("_dry_run"))
    return f"{head}pack {pack_name}_dry_run version {pack_version}\n{body.rstrip()}\n"


def rename_specs(body: str) -> tuple[str, int]:
    """`spec {` becomes `dry_run_spec {` — except a spec declaring `reset = true`.

    A pack that runs a managed constraint declares its superseded legacy twin OFF
    (`spec { reset = true }`), because absence is not enough: a policy already set on
    the organisation is invisible to an apply that does not declare it. That
    declaration is not a control being enforced and there is nothing to size about it,
    so it stays exactly as it is while its managed partner goes to dry run.
    """
    out, i, n = [], 0, 0
    for m in re.finditer(r"^(\s*)spec(\s*\{)", body, re.M):
        start, depth, j, opened = m.start(), 0, m.start(), False
        while j < len(body):
            if body[j] == "{":
                depth += 1
                opened = True
            elif body[j] == "}":
                depth -= 1
                if opened and depth == 0:
                    j += 1
                    break
            j += 1
        block = body[start:j]
        out.append(body[i:start])
        if re.search(r"^\s*reset\s*=\s*true\s*$", block, re.M):
            out.append(block)
        else:
            out.append(re.sub(r"^(\s*)spec(\s*\{)", r"\1dry_run_spec\2", block, count=1, flags=re.M))
            n += 1
        i = j
    out.append(body[i:])
    return "".join(out), n


def drop_claims(body: str) -> str:
    """Remove every top-level `claim … { … }`, braces balanced."""
    out, i = [], 0
    for m in re.finditer(r"^claim\s", body, re.M):
        start = m.start()
        depth, j, opened = 0, start, False
        while j < len(body):
            if body[j] == "{":
                depth += 1
                opened = True
            elif body[j] == "}":
                depth -= 1
                if opened and depth == 0:
                    j += 1
                    break
            j += 1
        out.append(body[i:start])
        i = j
    out.append(body[i:])
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any twin is stale")
    args = ap.parse_args()

    stale = []
    for stem, param in sorted(DRY_RUNNABLE.items()):
        src = EXT / f"{stem}.satz"
        if not src.exists():
            raise SystemExit(f"{src} does not exist — DRY_RUNNABLE names a fragment that is gone")
        want = derive(src.read_text(encoding="utf-8"), stem, param, f"{stem}.satz")
        dst = EXT / f"{stem}-dry-run.satz"
        if args.check:
            if not dst.exists() or dst.read_text(encoding="utf-8") != want:
                stale.append(dst.relative_to(ROOT))
        else:
            dst.write_text(want, encoding="utf-8")
            print(f"wrote {dst.relative_to(ROOT)}")

    if stale:
        print(
            "dry-run twins are stale:\n  "
            + "\n  ".join(str(p) for p in stale)
            + "\n\nRun: uv run scripts/build_dry_run_fragments.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print(f"dry-run twins: OK ({len(DRY_RUNNABLE)} fragments)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
