name = "Satz"
grammar = "satz"
path_suffixes = ["satz"]
line_comments = ["// ", "# "]
block_comment = ["/*", "*/"]
autoclose_before = ",]}"
tab_size = 2
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
