//! `satz doc-packs`: one Markdown page per pristine pack, DERIVED from the
//! parser — header comment, params with defaults, `use`s, resources, `hcl`
//! blocks, claims with witnesses, duties and interpretation — plus an index.
//! The hand-written part is a notes region the regeneration preserves.
//! `--check` fails when the committed pages are behind the packs: docs are
//! derived from the parser, never from intent.

use satz_core::satz::{self, Entry, File, Key, StrPart, Value};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

type BoxErr = Box<dyn std::error::Error>;

const NOTES_START: &str = "<!-- notes:start — hand-written, kept across `satz doc-packs` -->";
const NOTES_END: &str = "<!-- notes:end -->";
const BANNER: &str = "<!-- generated by `satz doc-packs` from the pack file — edit the pack or the notes region, never the rest -->";

/// Every pristine pack under `presets_dir`: (relative path, parsed file, source text).
fn packs(presets_dir: &Path) -> Result<Vec<(PathBuf, File, String)>, BoxErr> {
    let mut out = Vec::new();
    let mut stack = vec![presets_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = std::fs::read_dir(&dir).map_err(|e| format!("{}: {}", dir.display(), e))?;
        for e in entries {
            let p = e?.path();
            if p.is_dir() {
                if p.file_name().is_some_and(|n| n == "docs") {
                    continue;
                }
                stack.push(p);
                continue;
            }
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if !name.ends_with(".satz") || name.contains(".local.") || name.ends_with(".diff.satz") {
                continue;
            }
            let src = std::fs::read_to_string(&p).map_err(|e| format!("{}: {}", p.display(), e))?;
            let file = satz::parse(&src).map_err(|e| format!("{}:{}: {}", p.display(), e.line, e.msg))?;
            if !file.is_pack {
                return Err(format!("{}: not a pack (no `pack` header) — an estate does not belong in the preset library", p.display()).into());
            }
            out.push((p.strip_prefix(presets_dir)?.to_path_buf(), file, src));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

fn key_text(k: &Key) -> String {
    match k {
        Key::Ident(s) => s.clone(),
        Key::Str(parts) => str_text(parts),
    }
}

fn str_text(parts: &[StrPart]) -> String {
    parts
        .iter()
        .map(|p| match p {
            StrPart::Lit(s) => s.clone(),
            StrPart::Param(r) => format!("{{{}}}", r),
        })
        .collect()
}

/// A value as the reader would write it.
fn value_text(v: &Value) -> String {
    match v {
        Value::Str(parts) => format!("\"{}\"", str_text(parts)),
        Value::Num(n) => n.clone(),
        Value::Bool(b) => b.to_string(),
        Value::Ref(r) => r.clone(),
        Value::List(items) => {
            let inner: Vec<String> = items.iter().map(value_text).collect();
            if inner.is_empty() {
                "[]".into()
            } else {
                format!("[ {} ]", inner.join(", "))
            }
        }
        Value::Obj(entries) => format!("{{ {} }}", entries.iter().map(entry_text).collect::<Vec<_>>().join(" ")),
    }
}

fn entry_text(e: &Entry) -> String {
    match e {
        Entry::Attr { key, value, .. } => format!("{} = {}", key_text(key), value_text(value)),
        Entry::Map { key, name, body, .. } => {
            let n = name.as_ref().map(|n| format!(" {}", key_text(n))).unwrap_or_default();
            format!("{}{} {{ {} }}", key_text(key), n, body.iter().map(entry_text).collect::<Vec<_>>().join(" "))
        }
        Entry::Use { path, as_key, when, .. } => {
            let mut s = format!("use \"{}\"", path);
            if let Some(a) = as_key {
                s.push_str(&format!(" as {}", a));
            }
            if let Some(w) = when {
                s.push_str(&format!(" when {}", w));
            }
            s
        }
    }
}

/// The comment block above the `pack` header — the author's own statement
/// of purpose. The converter's provenance line is not purpose.
fn purpose(src: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in src.lines() {
        let t = line.trim();
        if t.starts_with("pack ") {
            break;
        }
        if let Some(c) = t.strip_prefix("//").or_else(|| t.strip_prefix('#')) {
            let c = c.trim();
            if c.starts_with("Converted by") || c.starts_with("Converted from") {
                continue;
            }
            out.push(c.to_string());
        } else if !t.is_empty() {
            break;
        }
    }
    while out.last().is_some_and(|l| l.is_empty()) {
        out.pop();
    }
    while out.first().is_some_and(|l| l.is_empty()) {
        out.remove(0);
    }
    out
}

/// What a pack contributes: typed resource maps (type → labels), bare labels
/// (keyed by the estate's map), attribute-shaped entries, and `use` lines.
#[derive(Default)]
struct Shape {
    typed: BTreeMap<String, Vec<String>>,
    bare: Vec<String>,
    uses: Vec<String>,
}

fn shape(items: &[Entry]) -> Shape {
    let mut s = Shape::default();
    for e in items {
        match e {
            Entry::Map { key, name: None, body, .. } => {
                let k = key_text(key);
                if k.starts_with("google_") {
                    let labels: Vec<String> = body
                        .iter()
                        .map(|b| match b {
                            Entry::Map { key, .. } => key_text(key),
                            Entry::Attr { key, .. } => format!("{} (grant map)", key_text(key)),
                            Entry::Use { .. } => entry_text(b),
                        })
                        .collect();
                    s.typed.entry(k).or_default().extend(labels);
                } else {
                    s.bare.push(k);
                }
            }
            Entry::Map { key, name: Some(n), .. } => s.bare.push(format!("{} {}", key_text(key), key_text(n))),
            Entry::Attr { key, .. } => s.bare.push(format!("{} (attribute)", key_text(key))),
            Entry::Use { .. } => s.uses.push(entry_text(e)),
        }
    }
    s
}

fn notes_region(existing: Option<&str>) -> String {
    if let Some(text) = existing {
        if let (Some(a), Some(b)) = (text.find(NOTES_START), text.find(NOTES_END)) {
            if a < b {
                return text[a..b + NOTES_END.len()].to_string();
            }
        }
    }
    format!("{}\n\n_No notes yet._\n\n{}", NOTES_START, NOTES_END)
}

fn render(rel: &Path, file: &File, src: &str, existing: Option<&str>) -> String {
    let name = file.estate.clone().unwrap_or_default();
    let version = file.version.clone().unwrap_or_else(|| "unversioned".into());
    let mut md = String::new();
    md.push_str(BANNER);
    md.push('\n');
    md.push_str(&format!("# `{}` — version {}{}\n\n", name, version, if file.content_mode { " · content pack" } else { "" }));
    md.push_str(&format!("Source: `presets/{}`", rel.display()));
    if file.content_mode {
        md.push_str(" — a **content** pack: forking it into `<name>.local.satz` is the expected workflow (per-customer content).");
    }
    md.push_str("\n\n");
    let p = purpose(src);
    if !p.is_empty() {
        md.push_str("## Purpose\n\n");
        md.push_str(&p.join("\n"));
        md.push_str("\n\n");
    }
    md.push_str("## Params\n\n");
    if file.params.is_empty() {
        md.push_str("_None — the pack takes everything from the estate's params._\n\n");
    } else {
        md.push_str("| param | default |\n|---|---|\n");
        for (n, v, _) in &file.params {
            md.push_str(&format!("| `{}` | `{}` |\n", n, value_text(v).replace('|', "\\|")));
        }
        md.push('\n');
    }
    let sh = shape(&file.items);
    md.push_str("## Contributes\n\n");
    if !sh.uses.is_empty() {
        for u in &sh.uses {
            md.push_str(&format!("- `{}`\n", u));
        }
        md.push('\n');
    }
    if !sh.typed.is_empty() {
        md.push_str("| resource type | labels |\n|---|---|\n");
        for (t, labels) in &sh.typed {
            md.push_str(&format!("| `{}` | {} |\n", t, labels.iter().map(|l| format!("`{}`", l)).collect::<Vec<_>>().join(", ")));
        }
        md.push('\n');
    }
    if !sh.bare.is_empty() {
        md.push_str(&format!(
            "A bare list — keyed by the estate's resource map (`google_x {{ use \"presets/{}\" }}` or `use … as google_x`): {}.\n\n",
            rel.display(),
            sh.bare.iter().map(|l| format!("`{}`", l)).collect::<Vec<_>>().join(", ")
        ));
    }
    if sh.typed.is_empty() && sh.bare.is_empty() && sh.uses.is_empty() {
        md.push_str("_No resources — params and claims only._\n\n");
    }
    if !file.hcl_blocks.is_empty() {
        md.push_str(&format!("**Raw HCL:** {} `hcl` block(s)", file.hcl_blocks.len()));
        let trusted: Vec<&str> = file.hcl_blocks.iter().filter_map(|h| h.trust.as_deref()).collect();
        if !trusted.is_empty() {
            md.push_str(&format!(" — trusted: {}", trusted.iter().map(|t| format!("\"{}\"", t)).collect::<Vec<_>>().join(", ")));
        }
        md.push_str(". Opaque to the compliance plane.\n\n");
    }
    if !file.suppressions.is_empty() {
        md.push_str(&format!("**Suppressions:** {}.\n\n", file.suppressions.len()));
    }
    // A pack that ships an executable step must say so on its own page. Whoever
    // installs it with `get-presets` should not have to open the .satz to find out
    // that `run-actions` would run something.
    if !file.actions.is_empty() {
        md.push_str(&format!(
            "**Actions:** {} — `satz run-actions` executes {}. Not covered by any claim.\n\n",
            file.actions.len(),
            file.actions
                .iter()
                .map(|a| format!("`{}` (`{}`)", a.name, a.run))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        for a in &file.actions {
            md.push_str(&format!("- `{}` — {}\n", a.name, a.reason));
        }
        md.push('\n');
    }
    md.push_str("## Claims\n\n");
    if file.claims.is_empty() {
        md.push_str("_None — this pack proves no control by itself._\n\n");
    } else {
        md.push_str("| framework | control | kind | witnesses | interpretation |\n|---|---|---|---|---|\n");
        for c in &file.claims {
            let kind = match c.coverage.as_str() {
                "deviates" => format!("**deviates** — {}", c.reason.clone().unwrap_or_default()),
                k => k.to_string(),
            };
            md.push_str(&format!(
                "| {} {} | {} | {} | {} | {} |\n",
                c.framework,
                c.version,
                c.control,
                kind,
                c.resources.iter().map(|r| format!("`{}`", r)).collect::<Vec<_>>().join("<br>"),
                c.interpretation.clone().unwrap_or_default().replace('|', "\\|")
            ));
        }
        md.push('\n');
        // one duty may serve the same control in two framework versions —
        // list it once, with every control it holds partial
        let mut duties: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();
        for c in &file.claims {
            for (id, text) in &c.duties {
                let controls = duties.entry((id.clone(), text.clone())).or_default();
                let tag = format!("{} {} §{}", c.framework, c.version, c.control);
                if !controls.contains(&tag) {
                    controls.push(tag);
                }
            }
        }
        if !duties.is_empty() {
            md.push_str("**Manual duties** (a control stays *partial* until each is attested):\n\n");
            for ((id, text), controls) in duties {
                md.push_str(&format!("- `{}` ({}) — {}\n", id, controls.join(", "), text.replace('\n', " ")));
            }
            md.push('\n');
        }
    }
    md.push_str("## Notes\n\n");
    md.push_str(&notes_region(existing));
    md.push('\n');
    md
}

fn index(rows: &[(&PathBuf, &File)]) -> String {
    let mut md = String::from(BANNER);
    md.push_str("\n# Preset packs\n\nOne page per pristine pack, derived from the pack file by `satz doc-packs`; the set's overview is [`presets/README.md`](../README.md), its history [`presets/CHANGELOG.md`](../CHANGELOG.md).\n\n| pack | version | file | resources | claims |\n|---|---|---|---|---|\n");
    for (rel, file) in rows {
        let sh = shape(&file.items);
        let resources: usize = sh.typed.values().map(|l| l.len()).sum::<usize>() + sh.bare.len();
        let stem = rel.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        md.push_str(&format!(
            "| [`{}`]({}.md) | {} | `{}` | {} | {} |\n",
            file.estate.clone().unwrap_or_default(),
            stem,
            file.version.clone().unwrap_or_else(|| "unversioned".into()),
            rel.display(),
            resources,
            file.claims.len()
        ));
    }
    md
}

/// Generate (or, with `check`, verify) `presets/docs/`.
/// Every claim in the library must name a control that exists in its
/// framework's catalog — `<presets_dir>/catalogs/<framework>-<version>.yaml`.
/// A claim on a control id the catalog does not carry proves nothing and
/// reports nothing: the CIS 4.0 alert claims were off by one for weeks with
/// no gate to say so. Returns the offending `(pack, framework version §id)`
/// pairs; a missing catalog file is itself an error.
pub(crate) fn check_claims_against_catalogs(presets_dir: &Path) -> Result<Vec<String>, BoxErr> {
    let mut catalogs: std::collections::BTreeMap<(String, String), std::collections::BTreeSet<String>> =
        std::collections::BTreeMap::new();
    let mut bad = Vec::new();
    for (rel, file, _) in packs(presets_dir)? {
        for c in &file.claims {
            let key = (c.framework.clone(), c.version.clone());
            if !catalogs.contains_key(&key) {
                let path = presets_dir.join("catalogs").join(format!("{}-{}.yaml", c.framework, c.version));
                let text = std::fs::read_to_string(&path).map_err(|e| {
                    format!("{}: claims {} {} but there is no catalog {} ({})", rel.display(), c.framework, c.version, path.display(), e)
                })?;
                let cat: crate::compliance::Catalog =
                    serde_yaml::from_str(&text).map_err(|e| format!("{}: {}", path.display(), e))?;
                catalogs.insert(key.clone(), cat.controls.keys().cloned().collect());
            }
            if !catalogs[&key].contains(&c.control) {
                bad.push(format!("{}: claim {} {} §{} — no such control in the catalog", rel.display(), c.framework, c.version, c.control));
            }
        }
    }
    Ok(bad)
}

pub(crate) fn run(presets_dir: &Path, out_dir: &Path, check: bool) -> Result<(), BoxErr> {
    if check {
        let bad = check_claims_against_catalogs(presets_dir)?;
        if !bad.is_empty() {
            return Err(format!(
                "{} claim(s) name a control their catalog does not carry:\n  {}",
                bad.len(),
                bad.join("\n  ")
            )
            .into());
        }
    }
    let all = packs(presets_dir)?;
    if all.is_empty() {
        return Err(format!("{}: no packs found", presets_dir.display()).into());
    }
    let mut stale = Vec::new();
    let mut written = 0;
    let mut pages: Vec<(PathBuf, String)> = Vec::new();
    for (rel, file, src) in &all {
        let stem = rel.file_stem().and_then(|s| s.to_str()).unwrap_or("pack");
        let out = out_dir.join(format!("{}.md", stem));
        let existing = std::fs::read_to_string(&out).ok();
        pages.push((out, render(rel, file, src, existing.as_deref())));
    }
    let idx_rows: Vec<(&PathBuf, &File)> = all.iter().map(|(r, f, _)| (r, f)).collect();
    pages.push((out_dir.join("README.md"), index(&idx_rows)));
    for (out, text) in pages {
        let current = std::fs::read_to_string(&out).ok();
        if current.as_deref() == Some(text.as_str()) {
            continue;
        }
        if check {
            stale.push(out);
        } else {
            std::fs::create_dir_all(out_dir)?;
            std::fs::write(&out, &text).map_err(|e| format!("{}: {}", out.display(), e))?;
            written += 1;
        }
    }
    if check {
        if !stale.is_empty() {
            return Err(format!(
                "doc-packs: {} page(s) behind the packs — run `satz doc-packs` and commit: {}",
                stale.len(),
                stale.iter().map(|p| p.display().to_string()).collect::<Vec<_>>().join(", ")
            )
            .into());
        }
        println!("doc-packs: {} page(s) current", all.len() + 1);
    } else {
        println!("doc-packs: {} pack(s), {} page(s) written to {}", all.len(), written, out_dir.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_pack_page_carries_purpose_params_resources_and_claims_and_keeps_notes() {
        let src = "// Log sink and bucket for the audit trail.\n// Second line.\n\npack docs_test version \"1.3\"\n\nparams {\n  bucket_location = \"EU\"\n  names = [ \"a\", \"b\" ]\n}\n\ngoogle_storage_bucket {\n  audit { name = \"{customer_shortname}-audit\" location = bucket_location }\n}\n\n\"compute-managed-requireOsLogin\" { name = \"x\" }\n\nclaim \"cis-gcp\" \"4.0\" \"2.2\" implements {\n  resources = [\"google_storage_bucket.audit\"]\n  interpretation = \"All entries land in the bucket.\"\n  duty_lock = \"Lock the bucket after validation.\"\n}\n";
        let file = satz::parse(src).unwrap();
        let existing = format!("old\n{}\nKeep me.\n{}\n", NOTES_START, NOTES_END);
        let md = render(Path::new("monitoring/x.satz"), &file, src, Some(&existing));
        assert!(md.contains("# `docs_test` — version 1.3"), "{}", md);
        assert!(md.contains("Log sink and bucket for the audit trail.\nSecond line."), "{}", md);
        assert!(md.contains("| `bucket_location` | `\"EU\"` |") && md.contains("| `names` | `[ \"a\", \"b\" ]` |"), "{}", md);
        assert!(md.contains("| `google_storage_bucket` | `audit` |"), "{}", md);
        assert!(md.contains("A bare list") && md.contains("`compute-managed-requireOsLogin`"), "{}", md);
        assert!(md.contains("| cis-gcp 4.0 | 2.2 | implements | `google_storage_bucket.audit` | All entries land in the bucket. |"), "{}", md);
        assert!(md.contains("- `lock` (cis-gcp 4.0 §2.2) — Lock the bucket after validation."), "{}", md);
        assert!(md.contains("Keep me."), "the notes region must survive regeneration:\n{}", md);
        assert!(!md.contains("Converted by"));
    }

    #[test]
    fn the_shipped_library_renders_and_is_current() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        run(&root.join("presets"), &root.join("presets/docs"), true).expect("presets/docs is behind the packs — run `satz doc-packs` and commit");
    }

    #[test]
    fn every_shipped_claim_names_a_control_its_catalog_carries() {
        // The gate that was missing when the CIS 4.0 alert claims drifted one
        // id off the benchmark: a claim on a control the catalog does not know
        // proves nothing and must not ship.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let bad = check_claims_against_catalogs(&root.join("presets")).expect("catalogs readable");
        assert!(bad.is_empty(), "claims off their catalog:\n{}", bad.join("\n"));
    }

    #[test]
    fn a_claim_on_an_unknown_control_is_reported() {
        let dir = std::env::temp_dir().join(format!("satz-claimgate-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("catalogs")).unwrap();
        std::fs::write(
            dir.join("catalogs/cis-gcp-4.0.yaml"),
            "catalog: cis-gcp\nversion: \"4.0\"\ncontrols:\n  \"2.4\":\n    title: \"x\"\n",
        )
        .unwrap();
        std::fs::write(
            dir.join("p.satz"),
            "pack p version \"1.0\"\n\nclaim \"cis-gcp\" \"4.0\" \"2.4\" implements { resources = [\"a.b\"] }\nclaim \"cis-gcp\" \"4.0\" \"2.99\" implements { resources = [\"a.b\"] }\n",
        )
        .unwrap();
        let bad = check_claims_against_catalogs(&dir).unwrap();
        assert_eq!(bad.len(), 1, "{:?}", bad);
        assert!(bad[0].contains("§2.99"), "{:?}", bad);
        // a framework with no catalog file is an error, not a pass
        std::fs::write(dir.join("q.satz"), "pack q version \"1.0\"\n\nclaim \"nist\" \"800-53\" \"AC-1\" implements { resources = [\"a.b\"] }\n").unwrap();
        assert!(check_claims_against_catalogs(&dir).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }
}
