//! `satz doc-packs`: one Markdown page per pristine pack, DERIVED from the
//! parser — header comment, the invocation that installs it, params with
//! defaults, resources, claims with their catalog titles, duties, and the
//! pack's own version history — plus an index of the library.
//! The hand-written part is a notes region the regeneration preserves.
//! `--check` fails when the committed pages are behind the packs: docs are
//! derived from the parser, never from intent.
//!
//! Every gate below runs on the WRITE path as much as under `--check`. A claim
//! on a control the catalog does not carry, a header with no summary, a pack
//! version with no changelog row: none of those may reach a page and be
//! discovered later. A generated page that is wrong is worse than none.

use satz_core::satz::{self, Entry, File, Key, StrPart, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

type BoxErr = Box<dyn std::error::Error>;

const NOTES_START: &str = "<!-- notes:start — hand-written, kept across `satz doc-packs` -->";
const NOTES_END: &str = "<!-- notes:end -->";
const BANNER: &str = "<!-- generated by `satz doc-packs` from the pack file — edit the pack or the notes region, never the rest -->";

/// The index prints the summary in a table cell; a paragraph does not fit one.
const SUMMARY_MAX: usize = 160;

/// Every pristine pack under `presets_dir`: (relative path, parsed file, source text).
fn packs(presets_dir: &Path) -> Result<Vec<(PathBuf, File, String)>, BoxErr> {
    let mut out = Vec::new();
    let mut stack = vec![presets_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = std::fs::read_dir(&dir).map_err(|e| format!("{}: {}", dir.display(), e))?;
        for e in entries {
            let p = e?.path();
            if p.is_dir() {
                if p.file_name().is_some_and(|n| n == "docs") {
                    continue;
                }
                stack.push(p);
                continue;
            }
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if !name.ends_with(".satz") || name.contains(".local.") || name.ends_with(".diff.satz") {
                continue;
            }
            let src = std::fs::read_to_string(&p).map_err(|e| format!("{}: {}", p.display(), e))?;
            let file = satz::parse(&src).map_err(|e| format!("{}:{}: {}", p.display(), e.line, e.msg))?;
            if !file.is_pack {
                return Err(format!("{}: not a pack (no `pack` header) — an estate does not belong in the preset library", p.display()).into());
            }
            out.push((p.strip_prefix(presets_dir)?.to_path_buf(), file, src));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

fn key_text(k: &Key) -> String {
    match k {
        Key::Ident(s) => s.clone(),
        Key::Str(parts) => str_text(parts),
    }
}

fn str_text(parts: &[StrPart]) -> String {
    parts
        .iter()
        .map(|p| match p {
            StrPart::Lit(s) => s.clone(),
            StrPart::Param(r) => format!("{{{}}}", r),
        })
        .collect()
}

/// A value as the reader would write it.
fn value_text(v: &Value) -> String {
    match v {
        Value::Str(parts) => format!("\"{}\"", str_text(parts)),
        Value::Num(n) => n.clone(),
        Value::Bool(b) => b.to_string(),
        Value::Ref(r) => r.clone(),
        Value::List(items) => {
            let inner: Vec<String> = items.iter().map(value_text).collect();
            if inner.is_empty() {
                "[]".into()
            } else {
                format!("[ {} ]", inner.join(", "))
            }
        }
        Value::Obj(entries) => format!("{{ {} }}", entries.iter().map(entry_text).collect::<Vec<_>>().join(" ")),
    }
}

fn entry_text(e: &Entry) -> String {
    match e {
        Entry::Attr { key, value, .. } => format!("{} = {}", key_text(key), value_text(value)),
        Entry::Map { key, name, body, .. } => {
            let n = name.as_ref().map(|n| format!(" {}", key_text(n))).unwrap_or_default();
            format!("{}{} {{ {} }}", key_text(key), n, body.iter().map(entry_text).collect::<Vec<_>>().join(" "))
        }
        Entry::Use { path, as_key, when, .. } => {
            let mut s = format!("use \"{}\"", path);
            if let Some(a) = as_key {
                s.push_str(&format!(" as {}", a));
            }
            if let Some(w) = when {
                s.push_str(&format!(" when {}", w));
            }
            s
        }
    }
}

/// A binding as a pack file writes it: one line when it fits, one item per line
/// when it does not.
fn value_block(name: &str, v: &Value, indent: &str) -> String {
    let one = format!("{}{} = {}", indent, name, value_text(v));
    if one.chars().count() <= 78 {
        return one;
    }
    if let Value::List(items) = v {
        let mut s = format!("{}{} = [\n", indent, name);
        for i in items {
            s.push_str(&format!("{}  {},\n", indent, value_text(i)));
        }
        s.push_str(&format!("{}]", indent));
        return s;
    }
    one
}

// ---------------------------------------------------------------------------
// The header comment: what the pack is for, and how it is used
// ---------------------------------------------------------------------------

/// The comment block above the `pack` header, split. The author's statement of
/// purpose, and the ONE canonical line saying how the pack is included — which
/// the page renders structurally, so it is lifted out of the prose rather than
/// printed twice. The converter's provenance line is neither.
#[derive(Default)]
struct Header {
    purpose: Vec<String>,
    invocation: Option<String>,
}

/// A header line is this pack's canonical invocation when it is a bare `use` of
/// the pack's OWN path, or a resource map wrapping one. A line naming ANOTHER
/// pack's path is prose about that pack and stays in the purpose.
fn is_invocation(line: &str, rel: &Path) -> bool {
    if !line.contains(&format!("\"presets/{}\"", rel.display())) {
        return false;
    }
    line.starts_with("use ") || (line.ends_with('}') && line.contains("{ use "))
}

fn header(src: &str, rel: &Path) -> Result<Header, BoxErr> {
    let mut h = Header::default();
    for line in src.lines() {
        let t = line.trim();
        if t.starts_with("pack ") {
            break;
        }
        let Some(c) = t.strip_prefix("//").or_else(|| t.strip_prefix('#')) else {
            if t.is_empty() {
                continue;
            }
            break;
        };
        let c = c.trim();
        if c.starts_with("Converted by") || c.starts_with("Converted from") {
            continue;
        }
        if is_invocation(c, rel) {
            if h.invocation.is_some() {
                return Err(format!(
                    "presets/{}: the header spells this pack's own `use` twice — the page renders it once, so one line has to be the canonical one",
                    rel.display()
                )
                .into());
            }
            h.invocation = Some(c.to_string());
            continue;
        }
        h.purpose.push(c.to_string());
    }
    // a lifted line leaves a blank run behind
    let mut trimmed: Vec<String> = Vec::new();
    for l in h.purpose {
        if l.is_empty() && trimmed.last().is_some_and(|p: &String| p.is_empty()) {
            continue;
        }
        trimmed.push(l);
    }
    while trimmed.last().is_some_and(|l| l.is_empty()) {
        trimmed.pop();
    }
    while trimmed.first().is_some_and(|l| l.is_empty()) {
        trimmed.remove(0);
    }
    h.purpose = trimmed;
    Ok(h)
}

/// The one line the index prints for this pack: the first sentence of the
/// header. Gated, because a heuristic over prose nobody is required to write is
/// how the index became a table of file names in the first place.
fn summary(h: &Header, rel: &Path) -> Result<String, BoxErr> {
    let at = |msg: &str| -> BoxErr { format!("presets/{}: {}", rel.display(), msg).into() };
    let first: Vec<&String> = h.purpose.iter().take_while(|l| !l.is_empty()).collect();
    if first.is_empty() {
        return Err(at("no header comment — the lines above `pack` are what the index prints for it; open with one sentence saying what it does"));
    }
    let para = first.iter().map(|l| l.as_str()).collect::<Vec<_>>().join(" ");
    if para.starts_with("http://") || para.starts_with("https://") {
        return Err(at("the summary is a bare URL — say what the pack does, and put the reference on a later line"));
    }
    if para.starts_with("Include") || para.starts_with("use \"") || para.contains("!include") {
        return Err(at("an include instruction where the summary should be — say what the pack DOES; how it is used goes on its own `use` line"));
    }
    // first sentence: a period followed by space and a capital, or the whole text
    let bytes: Vec<char> = para.chars().collect();
    let mut end = bytes.len();
    for i in 0..bytes.len().saturating_sub(2) {
        if bytes[i] == '.' && bytes[i + 1] == ' ' && bytes[i + 2].is_uppercase() {
            end = i + 1;
            break;
        }
    }
    let s: String = bytes[..end].iter().collect();
    if s.chars().count() > SUMMARY_MAX {
        return Err(at(&format!(
            "the first sentence is {} characters — the index prints it in a table cell; open with a short one and keep the detail below",
            s.chars().count()
        )));
    }
    Ok(s)
}

// ---------------------------------------------------------------------------
// What a pack contributes
// ---------------------------------------------------------------------------

/// One resource a pack contributes. `typ` is `None` for a bare-list pack, whose
/// resource map the estate supplies. `off` marks a policy declared with
/// `spec { reset = true }` — a superseded legacy twin, which proves nothing by
/// design and must not read as an unwitnessed resource.
struct Res {
    typ: Option<String>,
    label: String,
    off: bool,
}

/// What a pack contributes: typed resource maps (type → labels), bare labels
/// (keyed by the estate's map), attribute-shaped entries, and `use` lines.
#[derive(Default)]
struct Shape {
    typed: BTreeMap<String, Vec<String>>,
    bare: Vec<String>,
    uses: Vec<String>,
    /// the same resources, addressable — grant maps and nested `use`s excluded,
    /// because a grant's emitted address comes from its member and role, not
    /// from the key, and joining it to a witness would report every grant as
    /// unclaimed
    resources: Vec<Res>,
}

fn declared_off(body: &[Entry]) -> bool {
    body.iter().any(|e| match e {
        Entry::Map { key, body, .. } => {
            key_text(key) == "spec"
                && body.iter().any(|b| matches!(b, Entry::Attr { key, value: Value::Bool(true), .. } if key_text(key) == "reset"))
        }
        _ => false,
    })
}

fn shape(items: &[Entry]) -> Shape {
    let mut s = Shape::default();
    for e in items {
        match e {
            Entry::Map { key, name: None, body, .. } => {
                let k = key_text(key);
                if k.starts_with("google_") {
                    let labels: Vec<String> = body
                        .iter()
                        .map(|b| match b {
                            Entry::Map { key, body, .. } => {
                                s.resources.push(Res { typ: Some(k.clone()), label: key_text(key), off: declared_off(body) });
                                key_text(key)
                            }
                            Entry::Attr { key, .. } => format!("{} (grant map)", key_text(key)),
                            Entry::Use { .. } => entry_text(b),
                        })
                        .collect();
                    s.typed.entry(k).or_default().extend(labels);
                } else {
                    s.resources.push(Res { typ: None, label: k.clone(), off: declared_off(body) });
                    s.bare.push(k);
                }
            }
            Entry::Map { key, name: Some(n), .. } => s.bare.push(format!("{} {}", key_text(key), key_text(n))),
            Entry::Attr { key, .. } => s.bare.push(format!("{} (attribute)", key_text(key))),
            Entry::Use { .. } => s.uses.push(entry_text(e)),
        }
    }
    s
}

/// The resource type a bare-list pack's own claims say its labels land in.
/// One type resolves; none or several is the author's to state.
fn bare_type(file: &File) -> Option<String> {
    let types: BTreeSet<&str> = file.claims.iter().flat_map(|c| &c.resources).filter_map(|r| r.split('.').next()).collect();
    match types.len() {
        1 => types.into_iter().next().map(str::to_string),
        _ => None,
    }
}

/// The line that installs this pack, from the header when it states one and
/// from the pack's own shape when it does not. Never a guess: a pack whose shape
/// does not decide it has to say so itself.
fn invocation(rel: &Path, file: &File, sh: &Shape, h: &Header) -> Result<String, BoxErr> {
    if let Some(inv) = &h.invocation {
        return Ok(inv.clone());
    }
    let path = format!("\"presets/{}\"", rel.display());
    if !sh.typed.is_empty() && !sh.bare.is_empty() {
        return Err(format!(
            "presets/{}: the pack mixes typed resource maps with bare labels, so neither `use` form fits it — split it, or state the canonical line in the header",
            rel.display()
        )
        .into());
    }
    if !sh.typed.is_empty() || sh.bare.is_empty() {
        return Ok(format!("use {}", path));
    }
    match bare_type(file) {
        Some(t) => Ok(format!("{} {{ use {} }}", t, path)),
        None => Err(format!(
            "presets/{}: nothing says how this pack is used. It is a bare list of labels, so the estate keys it by a \
             resource map and the pack has to name which one — add the canonical line to the header comment, e.g.\n    \
             google_organization_iam_member {{ use {} }}",
            rel.display(),
            path
        )
        .into()),
    }
}

// ---------------------------------------------------------------------------
// Params a pack reads but does not declare
// ---------------------------------------------------------------------------

fn refs_in_str(parts: &[StrPart], out: &mut BTreeSet<String>) {
    for p in parts {
        if let StrPart::Param(r) = p {
            out.insert(r.clone());
        }
    }
}

fn refs_in_key(k: &Key, out: &mut BTreeSet<String>) {
    if let Key::Str(parts) = k {
        refs_in_str(parts, out);
    }
}

fn refs_in_value(v: &Value, out: &mut BTreeSet<String>) {
    match v {
        Value::Str(parts) => refs_in_str(parts, out),
        // a bare identifier in value position is a param; a reference to another
        // resource is `${{…}}`, which reaches here as literal string text
        Value::Ref(r) if r.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') => {
            out.insert(r.clone());
        }
        Value::List(items) => items.iter().for_each(|i| refs_in_value(i, out)),
        Value::Obj(entries) => entries.iter().for_each(|e| refs_in_entry(e, out)),
        _ => {}
    }
}

fn refs_in_entry(e: &Entry, out: &mut BTreeSet<String>) {
    match e {
        Entry::Attr { key, value, .. } => {
            refs_in_key(key, out);
            refs_in_value(value, out);
        }
        Entry::Map { key, name, body, .. } => {
            refs_in_key(key, out);
            if let Some(n) = name {
                refs_in_key(n, out);
            }
            body.iter().for_each(|b| refs_in_entry(b, out));
        }
        Entry::Use { when, .. } => {
            if let Some(w) = when {
                out.insert(w.clone());
            }
        }
    }
}

/// Params the pack reads and does not declare. Exact, not a heuristic: an
/// unresolved reference is a pipeline error, so "not declared here" is precisely
/// "the estate, or another pack, must supply it".
fn needs(file: &File) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    file.items.iter().for_each(|e| refs_in_entry(e, &mut out));
    for (_, v, _) in &file.params {
        refs_in_value(v, &mut out);
    }
    for a in &file.actions {
        a.args.iter().chain(&a.execute_args).for_each(|p| refs_in_str(p, &mut out));
    }
    let declared: BTreeSet<&str> = file.params.iter().map(|(n, _, _)| n.as_str()).collect();
    out.retain(|n| !declared.contains(n.as_str()));
    out
}

/// Which pack declares which param, across the whole library.
type Library = BTreeMap<String, Vec<String>>;

fn library(all: &[(PathBuf, File, String)]) -> Library {
    let mut lib: Library = BTreeMap::new();
    for (_, file, _) in all {
        let name = file.estate.clone().unwrap_or_default();
        for (p, _, _) in &file.params {
            let owners = lib.entry(p.clone()).or_default();
            if !owners.contains(&name) {
                owners.push(name.clone());
            }
        }
    }
    lib
}

// ---------------------------------------------------------------------------
// The catalogs, and the changelog
// ---------------------------------------------------------------------------

type Catalogs = BTreeMap<(String, String), crate::compliance::Catalog>;

/// Every catalog the library's claims cite, loaded once and validated.
///
/// A framework with no catalog file, and a claim on a control the catalog does
/// not carry, are hard errors HERE — on the write path as much as under
/// `--check`, because the control's title is now rendered onto the page and a
/// blank title is exactly how a claim on a wrong id survives review. The CIS 4.0
/// alert claims were one id off the benchmark for weeks with no gate to say so.
fn catalogs(presets_dir: &Path, all: &[(PathBuf, File, String)]) -> Result<Catalogs, BoxErr> {
    let mut cats: Catalogs = BTreeMap::new();
    let mut bad = Vec::new();
    for (rel, file, _) in all {
        for c in &file.claims {
            let key = (c.framework.clone(), c.version.clone());
            if !cats.contains_key(&key) {
                let path = presets_dir.join("catalogs").join(format!("{}-{}.yaml", c.framework, c.version));
                let text = std::fs::read_to_string(&path).map_err(|e| {
                    format!("{}: claims {} {} but there is no catalog {} ({})", rel.display(), c.framework, c.version, path.display(), e)
                })?;
                let cat: crate::compliance::Catalog =
                    serde_yaml::from_str(&text).map_err(|e| format!("{}: {}", path.display(), e))?;
                cats.insert(key.clone(), cat);
            }
            if !cats[&key].controls.contains_key(&c.control) {
                bad.push(format!("{}: claim {} {} §{} — no such control in the catalog", rel.display(), c.framework, c.version, c.control));
            }
        }
    }
    if !bad.is_empty() {
        return Err(format!("{} claim(s) name a control their catalog does not carry:\n  {}", bad.len(), bad.join("\n  ")).into());
    }
    Ok(cats)
}

fn control<'a>(cats: &'a Catalogs, c: &satz::ClaimDecl) -> &'a crate::compliance::Control {
    cats.get(&(c.framework.clone(), c.version.clone()))
        .and_then(|cat| cat.controls.get(&c.control))
        .expect("catalogs() rejected every claim whose control its catalog does not carry")
}

/// One row of the changelog table at the foot of `presets/README.md`.
#[derive(Debug)]
struct Change {
    version: String,
    date: String,
    change: String,
}

type Changelog = BTreeMap<String, Vec<Change>>;

/// Split a Markdown table row on its unescaped pipes.
fn cells(row: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut escaped = false;
    for ch in row.trim().trim_start_matches('|').trim_end_matches('|').chars() {
        if escaped {
            cur.push(ch);
            escaped = false;
        } else if ch == '\\' {
            escaped = true;
            cur.push(ch);
        } else if ch == '|' {
            out.push(cur.trim().to_string());
            cur = String::new();
        } else {
            cur.push(ch);
        }
    }
    out.push(cur.trim().to_string());
    out
}

/// The pack history, read from the `## Changelog` table in `presets/README.md`.
///
/// Two gates ride along, and both used to live in a shell loop in the smoke
/// matrix: every row names a pack that exists, and every pack's current in-file
/// version has a row. Here they also run under `cargo test`, and the message can
/// name the line.
fn changelog(presets_dir: &Path, all: &[(PathBuf, File, String)]) -> Result<Changelog, BoxErr> {
    let path = presets_dir.join("README.md");
    let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {}", path.display(), e))?;
    let lines: Vec<&str> = text.lines().collect();
    let at = |n: usize, msg: &str| -> BoxErr { format!("{}:{}: {}", path.display(), n + 1, msg).into() };

    let start = lines
        .iter()
        .position(|l| l.trim() == "## Changelog")
        .ok_or_else(|| -> BoxErr { format!("{}: no `## Changelog` section — the pack history lives at the foot of the preset library", path.display()).into() })?;
    let head = (start + 1..lines.len())
        .find(|&i| lines[i].trim_start().starts_with('|'))
        .ok_or_else(|| at(start, "the `## Changelog` section carries no table"))?;
    let want = ["pack", "version", "date", "change"];
    if cells(lines[head]) != want {
        return Err(at(head, "the changelog table's header must read `| pack | version | date | change |`"));
    }
    if !lines[head + 1].trim().chars().all(|c| matches!(c, '|' | '-' | ':' | ' ')) {
        return Err(at(head + 1, "the changelog table's header is not followed by a separator row"));
    }

    let known: BTreeSet<String> = all.iter().map(|(_, f, _)| f.estate.clone().unwrap_or_default()).collect();
    let mut hist: Changelog = BTreeMap::new();
    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    for (n, row) in lines.iter().enumerate().skip(head + 2) {
        if !row.trim_start().starts_with('|') {
            break;
        }
        let c = cells(row);
        if c.len() != 4 {
            return Err(at(n, &format!("a changelog row has {} cells, not 4", c.len())));
        }
        let pack = c[0].trim_matches('`').to_string();
        if pack == c[0] {
            return Err(at(n, "the pack name in a changelog row must be in backticks"));
        }
        if !known.contains(&pack) {
            return Err(at(n, &format!("changelog row for `{}`, which is not a pack in the library", pack)));
        }
        if !seen.insert((pack.clone(), c[1].clone())) {
            return Err(at(n, &format!("`{}` {} has two changelog rows", pack, c[1])));
        }
        hist.entry(pack).or_default().push(Change { version: c[1].clone(), date: c[2].clone(), change: c[3].clone() });
    }

    let mut missing = Vec::new();
    for (rel, file, _) in all {
        let name = file.estate.clone().unwrap_or_default();
        let version = file.version.clone().unwrap_or_default();
        if !hist.get(&name).is_some_and(|rows| rows.iter().any(|r| r.version == version)) {
            missing.push(format!("presets/{}: `{}` {} has no changelog row", rel.display(), name, version));
        }
    }
    if !missing.is_empty() {
        return Err(format!(
            "{} pack version(s) with no row under `## Changelog` in presets/README.md — a bump and its reason ship together:\n  {}",
            missing.len(),
            missing.join("\n  ")
        )
        .into());
    }
    Ok(hist)
}

// ---------------------------------------------------------------------------
// The page
// ---------------------------------------------------------------------------

/// `google_x` + `some-label` → the address the emitter writes, which is the
/// address a claim witnesses.
fn address(typ: &str, label: &str) -> String {
    format!("{}.{}", typ, label.replace('-', "_"))
}

fn use_it(rel: &Path, file: &File, sh: &Shape, h: &Header, lib: &Library) -> Result<String, BoxErr> {
    let inv = invocation(rel, file, sh, h)?;
    let gate = inv.split(" when ").nth(1).map(|s| s.trim().to_string());

    let mut md = String::from("## Use it\n\n```\n");
    if gate.is_some() || !file.params.is_empty() {
        md.push_str("params {\n");
        if let Some(g) = &gate {
            md.push_str(&format!("  {} = true\n", g));
            if !file.params.is_empty() {
                md.push('\n');
            }
        }
        if !file.params.is_empty() {
            md.push_str("  // the pack's own defaults — copy only the lines you change\n");
            for (n, v, _) in &file.params {
                md.push_str(&value_block(n, v, "  "));
                md.push('\n');
            }
        }
        md.push_str("}\n\n");
    }
    md.push_str(&inv);
    md.push_str("\n```\n\n");

    if let Some(g) = &gate {
        let by = lib.get(g).map(|packs| {
            packs.iter().map(|p| format!("`{}`", p)).collect::<Vec<_>>().join(", ")
        });
        md.push_str(&format!(
            "`{}` is the gate: while it is falsy the pack contributes nothing — no resources, no params, no claims. {}\n\n",
            g,
            match by {
                Some(p) => format!("It is declared by {}, and the estate's own binding wins.", p),
                None => "The param must be DECLARED somewhere — a `when` on a param nobody declares is an error, not `false`.".into(),
            }
        ));
    }
    if file.params.is_empty() && gate.is_none() {
        md.push_str("The pack declares no params: everything it sets is fixed in the file. A different value is a param lifted into the pack, or a `.local` fork.\n\n");
    }

    let outside = needs(file);
    if !outside.is_empty() {
        md.push_str("**Needs from outside the pack:**\n\n");
        for n in &outside {
            match lib.get(n) {
                Some(packs) => md.push_str(&format!(
                    "- `{}` — declared by {}; use one of them alongside, or declare it in the estate.\n",
                    n,
                    packs.iter().map(|p| format!("`{}`", p)).collect::<Vec<_>>().join(", ")
                )),
                None => md.push_str(&format!("- `{}` — no pack in the library declares it, so the estate must.\n", n)),
            }
        }
        md.push('\n');
    }
    Ok(md)
}

/// Which contributed resources no claim on this page witnesses — and, of those,
/// which are superseded legacy twins declared off, which prove nothing by design.
fn claim_coverage(sh: &Shape, file: &File) -> String {
    let witnesses: BTreeSet<&str> = file.claims.iter().flat_map(|c| &c.resources).map(String::as_str).collect();
    let bare = bare_type(file);
    let mut unclaimed = Vec::new();
    for r in &sh.resources {
        let Some(typ) = r.typ.as_deref().or(bare.as_deref()) else { continue };
        let addr = address(typ, &r.label);
        if witnesses.contains(addr.as_str()) {
            continue;
        }
        unclaimed.push(if r.off {
            format!("- `{}` — declared OFF (`spec {{ reset = true }}`): a superseded legacy twin, which proves nothing by design.\n", addr)
        } else {
            format!("- `{}` — contributed, but no claim names it.\n", addr)
        });
    }
    if unclaimed.is_empty() {
        return "Every resource this pack contributes is a witness of a claim above.\n\n".into();
    }
    format!("Not every resource this pack contributes is a witness:\n\n{}\n", unclaimed.concat())
}

fn render(
    rel: &Path,
    file: &File,
    h: &Header,
    existing: Option<&str>,
    cats: &Catalogs,
    history: &[Change],
    lib: &Library,
) -> Result<String, BoxErr> {
    let name = file.estate.clone().unwrap_or_default();
    let version = file.version.clone().unwrap_or_else(|| "unversioned".into());
    let sh = shape(&file.items);
    let mut md = String::new();
    md.push_str(BANNER);
    md.push('\n');
    md.push_str(&format!("# `{}` — version {}{}\n\n", name, version, if file.content_mode { " · content pack" } else { "" }));
    md.push_str(&format!("Source: `presets/{}`", rel.display()));
    if file.content_mode {
        md.push_str(" — a **content** pack: forking it into `<name>.local.satz` is the expected workflow (per-customer content).");
    }
    md.push_str("\n\n");
    if !h.purpose.is_empty() {
        md.push_str("## Purpose\n\n");
        md.push_str(&h.purpose.join("\n"));
        md.push_str("\n\n");
    }
    md.push_str(&use_it(rel, file, &sh, h, lib)?);
    md.push_str("## Params\n\n");
    if file.params.is_empty() {
        md.push_str("_None — the pack takes everything from the estate's params._\n\n");
    } else {
        md.push_str("| param | default |\n|---|---|\n");
        for (n, v, _) in &file.params {
            md.push_str(&format!("| `{}` | `{}` |\n", n, value_text(v).replace('|', "\\|")));
        }
        md.push('\n');
    }
    // A SECTION, not a column on the params table: a column rewrites all 25
    // generated pages, a section touches only packs that declare a question.
    if !file.questions.is_empty() {
        md.push_str("## Questions\n\n");
        md.push_str("What to ask before this pack is configured, and what changing the answer costs.\n\n");
        md.push_str("| asks about | prompt | reversal | blast | recommends |\n|---|---|---|---|---|\n");
        for q in &file.questions {
            md.push_str(&format!(
                "| `{}`{} | {} | {} | {} | {} |\n",
                q.subject,
                if q.oneof { " *(choice)*" } else { "" },
                q.prompt.replace('|', "\\|"),
                q.reversal.as_str(),
                q.blast.as_str(),
                q.recommend.as_ref().map(|v| format!("`{}`", value_text(v).replace('|', "\\|"))).unwrap_or_else(|| "—".into()),
            ));
        }
        md.push('\n');
        for q in &file.questions {
            if q.options.is_empty() && q.why.is_none() {
                continue;
            }
            md.push_str(&format!("**{}** — {}\n\n", q.subject, q.why.as_deref().unwrap_or("")));
            for o in &q.options {
                md.push_str(&format!(
                    "- `{}` — {}{}\n",
                    o.param,
                    o.label,
                    o.why.as_ref().map(|w| format!(" ({})", w)).unwrap_or_default()
                ));
            }
            md.push('\n');
        }
    }

    let off: BTreeSet<&str> = sh.resources.iter().filter(|r| r.off).map(|r| r.label.as_str()).collect();
    let mark = |l: &String| if off.contains(l.as_str()) { format!("`{}` *(off)*", l) } else { format!("`{}`", l) };
    md.push_str("## Contributes\n\n");
    if !sh.uses.is_empty() {
        for u in &sh.uses {
            md.push_str(&format!("- `{}`\n", u));
        }
        md.push('\n');
    }
    if !sh.typed.is_empty() {
        md.push_str("| resource type | labels |\n|---|---|\n");
        for (t, labels) in &sh.typed {
            md.push_str(&format!("| `{}` | {} |\n", t, labels.iter().map(mark).collect::<Vec<_>>().join(", ")));
        }
        md.push('\n');
    }
    if !sh.bare.is_empty() {
        md.push_str(&format!(
            "A bare list — keyed by the estate's resource map (`google_x {{ use \"presets/{}\" }}` or `use … as google_x`): {}.\n\n",
            rel.display(),
            sh.bare.iter().map(mark).collect::<Vec<_>>().join(", ")
        ));
    }
    if sh.typed.is_empty() && sh.bare.is_empty() && sh.uses.is_empty() {
        // A pack whose whole content is an action declares no resources on
        // purpose — saying "params and claims only" there would describe it as
        // missing something it was never meant to have.
        if file.actions.is_empty() {
            md.push_str("_No resources — params and claims only._\n\n");
        } else {
            md.push_str("_No resources: this pack's content is the action below — a step with no provider binding._\n\n");
        }
    }
    if !file.hcl_blocks.is_empty() {
        md.push_str(&format!("**Raw HCL:** {} `hcl` block(s)", file.hcl_blocks.len()));
        let trusted: Vec<&str> = file.hcl_blocks.iter().filter_map(|h| h.trust.as_deref()).collect();
        if !trusted.is_empty() {
            md.push_str(&format!(" — trusted: {}", trusted.iter().map(|t| format!("\"{}\"", t)).collect::<Vec<_>>().join(", ")));
        }
        md.push_str(". Opaque to the compliance plane.\n\n");
    }
    if !file.suppressions.is_empty() {
        md.push_str(&format!("**Suppressions:** {}.\n\n", file.suppressions.len()));
    }
    // A pack that ships an executable step must say so on its own page. Whoever
    // installs it with `get-presets` should not have to open the .satz to find out
    // that `run-actions` would run something.
    if !file.actions.is_empty() {
        md.push_str(&format!(
            "**Actions:** {} — `satz run-actions` executes {}. Not covered by any claim.\n\n",
            file.actions.len(),
            file.actions
                .iter()
                .map(|a| format!("`{}` (`{}`)", a.name, a.run))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        for a in &file.actions {
            md.push_str(&format!("- `{}` — {} (phase `{}`)\n", a.name, a.reason, a.phase));
        }
        md.push('\n');
    }
    md.push_str("## Claims\n\n");
    if file.claims.is_empty() {
        md.push_str("_None — this pack proves no control by itself._\n\n");
    } else {
        md.push_str("| framework | control | title | kind | witnesses | interpretation |\n|---|---|---|---|---|---|\n");
        for c in &file.claims {
            let kind = match c.coverage.as_str() {
                "deviates" => format!("**deviates** — {}", c.reason.clone().unwrap_or_default()),
                k => k.to_string(),
            };
            md.push_str(&format!(
                "| {} {} | {} | {} | {} | {} | {} |\n",
                c.framework,
                c.version,
                c.control,
                control(cats, c).title.replace('|', "\\|"),
                kind,
                c.resources.iter().map(|r| format!("`{}`", r)).collect::<Vec<_>>().join("<br>"),
                c.interpretation.clone().unwrap_or_default().replace('|', "\\|")
            ));
        }
        md.push('\n');
        // 4.0 and 5.0 carry identical titles and paraphrases for most controls —
        // fold them the way the duties below are folded, or the same sentence
        // appears twice under every claim pair.
        let mut asks: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();
        for c in &file.claims {
            let ctl = control(cats, c);
            let tag = format!("{} {} §{}", c.framework, c.version, c.control);
            let e = asks.entry((ctl.title.clone(), ctl.paraphrase.clone())).or_default();
            if !e.contains(&tag) {
                e.push(tag);
            }
        }
        md.push_str("**What the controls ask** (this project's paraphrase from the catalog — never the framework's own text):\n\n");
        for ((title, paraphrase), tags) in &asks {
            md.push_str(&format!("- **{}** ({})", title, tags.join(", ")));
            if !paraphrase.is_empty() {
                md.push_str(&format!(" — {}", paraphrase));
            }
            md.push('\n');
        }
        md.push('\n');
        // one duty may serve the same control in two framework versions —
        // list it once, with every control it holds partial
        let mut duties: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();
        for c in &file.claims {
            for (id, text) in &c.duties {
                let controls = duties.entry((id.clone(), text.clone())).or_default();
                let tag = format!("{} {} §{}", c.framework, c.version, c.control);
                if !controls.contains(&tag) {
                    controls.push(tag);
                }
            }
        }
        if !duties.is_empty() {
            md.push_str("**Manual duties** (a control stays *partial* until each is attested):\n\n");
            for ((id, text), controls) in duties {
                md.push_str(&format!("- `{}` ({}) — {}\n", id, controls.join(", "), text.replace('\n', " ")));
            }
            md.push('\n');
        }
        md.push_str(&claim_coverage(&sh, file));
    }
    md.push_str("## History\n\n");
    md.push_str("| version | date | change |\n|---|---|---|\n");
    for c in history {
        md.push_str(&format!("| {} | {} | {} |\n", c.version, c.date, c.change));
    }
    md.push_str("\nThe whole library's history: [the changelog](../README.md#changelog) in `presets/README.md`.\n\n");
    md.push_str("## Notes\n\n");
    md.push_str(&notes_region(existing));
    md.push('\n');
    Ok(md)
}

fn notes_region(existing: Option<&str>) -> String {
    if let Some(text) = existing {
        if let (Some(a), Some(b)) = (text.find(NOTES_START), text.find(NOTES_END)) {
            if a < b {
                return text[a..b + NOTES_END.len()].to_string();
            }
        }
    }
    format!("{}\n\n_No notes yet._\n\n{}", NOTES_START, NOTES_END)
}

// ---------------------------------------------------------------------------
// The index
// ---------------------------------------------------------------------------

/// The directory a pack lives in — the library's own grouping.
fn family(rel: &Path) -> String {
    rel.parent().map(|p| p.to_string_lossy().to_string()).unwrap_or_default()
}

/// Control ids sort as numbers, not as text: 1.10 comes after 1.9.
fn control_order(id: &str) -> Vec<u32> {
    id.split('.').map(|p| p.parse().unwrap_or(u32::MAX)).collect()
}

struct Row {
    rel: PathBuf,
    name: String,
    version: String,
    summary: String,
    resources: usize,
    frameworks: Vec<String>,
    claims: usize,
    /// (framework, version, control) — what the coverage table counts
    claimed: Vec<(String, String, String)>,
}

fn index(rows: &[Row], cats: &Catalogs) -> String {
    let mut md = String::from(BANNER);
    md.push_str("\n# Preset packs\n\n");
    md.push_str(
        "One page per pristine pack, derived from the pack file by `satz doc-packs`. The library's \
         conventions and its per-family prose are [`presets/README.md`](../README.md); its version \
         history is [the changelog](../README.md#changelog) at the foot of that page, repeated per \
         pack under **History** on each page here.\n\n",
    );
    let resources: usize = rows.iter().map(|r| r.resources).sum();
    let claims: usize = rows.iter().map(|r| r.claims).sum();
    let frameworks: Vec<String> = cats.keys().map(|(f, v)| format!("{} {}", f, v)).collect();
    md.push_str(&format!(
        "**{} packs · {} resources · {} claims{}.**\n\n",
        rows.len(),
        resources,
        claims,
        if frameworks.is_empty() { String::new() } else { format!(" over {}", frameworks.join(" and ")) }
    ));

    let mut families: BTreeMap<String, Vec<&Row>> = BTreeMap::new();
    for r in rows {
        families.entry(family(&r.rel)).or_default().push(r);
    }
    // the root family first, then the directories alphabetically
    let mut order: Vec<&String> = families.keys().collect();
    order.sort_by_key(|f| (!f.is_empty(), (*f).clone()));
    for fam in order {
        md.push_str(&match fam.is_empty() {
            true => "## Root — `presets/*.satz`\n\n".to_string(),
            false => format!("## `{}/`\n\n", fam),
        });
        md.push_str("| pack | version | what it does | resources | claims |\n|---|---|---|---|---|\n");
        for r in &families[fam] {
            let stem = r.rel.file_stem().and_then(|s| s.to_str()).unwrap_or("");
            md.push_str(&format!(
                "| [`{}`]({}.md) | {} | {} | {} | {} |\n",
                r.name,
                stem,
                r.version,
                r.summary.replace('|', "\\|"),
                r.resources,
                match r.claims {
                    0 => "—".to_string(),
                    n => format!("{} — {}", n, r.frameworks.join(", ")),
                }
            ));
        }
        md.push('\n');
    }

    if !cats.is_empty() {
        md.push_str("## Framework coverage\n\n");
        md.push_str(
            "What some pack in this library CLAIMS — never a verdict on an estate. A claim is proof \
             only once its witnesses are emitted; `satz require <framework> <estate>` judges an \
             estate.\n\n",
        );
        md.push_str("| framework | controls in the catalog | claimed by a pack | claimed by none |\n|---|---|---|---|\n");
        for ((f, v), cat) in cats {
            let claimed: BTreeSet<&str> = rows
                .iter()
                .flat_map(|r| &r.claimed)
                .filter(|(cf, cv, _)| cf == f && cv == v)
                .map(|(_, _, id)| id.as_str())
                .collect();
            let mut gaps: Vec<&String> = cat.controls.keys().filter(|k| !claimed.contains(k.as_str())).collect();
            gaps.sort_by_key(|id| control_order(id));
            md.push_str(&format!(
                "| {} {} | {} | {} | {} |\n",
                f,
                v,
                cat.controls.len(),
                claimed.len(),
                if gaps.is_empty() { "—".to_string() } else { gaps.iter().map(|g| g.as_str()).collect::<Vec<_>>().join(", ") }
            ));
        }
        md.push('\n');
    }
    md
}

/// Generate (or, with `check`, verify) `presets/docs/`.
pub(crate) fn run(presets_dir: &Path, out_dir: &Path, check: bool) -> Result<(), BoxErr> {
    let all = packs(presets_dir)?;
    if all.is_empty() {
        return Err(format!("{}: no packs found", presets_dir.display()).into());
    }
    let cats = catalogs(presets_dir, &all)?;
    let hist = changelog(presets_dir, &all)?;
    let lib = library(&all);

    // Header problems are collected and reported together: fixing them is one
    // pass over the library, not nine rounds of one error each.
    let mut headers = Vec::new();
    let mut errs = Vec::new();
    for (rel, _, src) in &all {
        match header(src, rel) {
            Ok(h) => headers.push(h),
            Err(e) => {
                errs.push(e.to_string());
                headers.push(Header::default());
            }
        }
    }
    let mut summaries = Vec::new();
    for ((rel, _, _), h) in all.iter().zip(&headers) {
        match summary(h, rel) {
            Ok(s) => summaries.push(s),
            Err(e) => {
                errs.push(e.to_string());
                summaries.push(String::new());
            }
        }
    }
    if !errs.is_empty() {
        return Err(format!("{} pack header(s) need work:\n  {}", errs.len(), errs.join("\n  ")).into());
    }

    let mut stale = Vec::new();
    let mut written = 0;
    let mut pages: Vec<(PathBuf, String)> = Vec::new();
    let mut rows: Vec<Row> = Vec::new();
    let empty: Vec<Change> = Vec::new();
    for (((rel, file, _), h), sum) in all.iter().zip(&headers).zip(&summaries) {
        let stem = rel.file_stem().and_then(|s| s.to_str()).unwrap_or("pack");
        let out = out_dir.join(format!("{}.md", stem));
        let existing = std::fs::read_to_string(&out).ok();
        let name = file.estate.clone().unwrap_or_default();
        let history = hist.get(&name).unwrap_or(&empty);
        pages.push((out, render(rel, file, h, existing.as_deref(), &cats, history, &lib)?));
        let sh = shape(&file.items);
        let mut frameworks: Vec<String> = file.claims.iter().map(|c| format!("{} {}", c.framework, c.version)).collect();
        frameworks.sort();
        frameworks.dedup();
        rows.push(Row {
            rel: rel.clone(),
            name,
            version: file.version.clone().unwrap_or_else(|| "unversioned".into()),
            summary: sum.clone(),
            resources: sh.typed.values().map(|l| l.len()).sum::<usize>() + sh.bare.len(),
            frameworks,
            claims: file.claims.len(),
            claimed: file
                .claims
                .iter()
                .map(|c| (c.framework.clone(), c.version.clone(), c.control.clone()))
                .collect(),
        });
    }
    pages.push((out_dir.join("README.md"), index(&rows, &cats)));
    for (out, text) in pages {
        let current = std::fs::read_to_string(&out).ok();
        if current.as_deref() == Some(text.as_str()) {
            continue;
        }
        if check {
            stale.push(out);
        } else {
            std::fs::create_dir_all(out_dir)?;
            std::fs::write(&out, &text).map_err(|e| format!("{}: {}", out.display(), e))?;
            written += 1;
        }
    }
    if check {
        if !stale.is_empty() {
            return Err(format!(
                "doc-packs: {} page(s) behind the packs — run `satz doc-packs` and commit: {}",
                stale.len(),
                stale.iter().map(|p| p.display().to_string()).collect::<Vec<_>>().join(", ")
            )
            .into());
        }
        println!("doc-packs: {} page(s) current", all.len() + 1);
    } else {
        println!("doc-packs: {} pack(s), {} page(s) written to {}", all.len(), written, out_dir.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog(yaml: &str) -> Catalogs {
        let cat: crate::compliance::Catalog = serde_yaml::from_str(yaml).unwrap();
        let key = (cat.catalog.clone(), cat.version.clone());
        BTreeMap::from([(key, cat)])
    }

    #[test]
    fn a_typed_pack_page_carries_use_purpose_params_claims_titles_history_and_keeps_notes() {
        let src = "// Log sink and bucket for the audit trail.\n// Second line.\n\npack docs_test version \"1.3\"\n\nparams {\n  bucket_location = \"EU\"\n  names = [ \"a\", \"b\" ]\n}\n\ngoogle_storage_bucket {\n  audit { name = \"{customer_shortname}-audit\" location = bucket_location }\n}\n\nclaim \"cis-gcp\" \"4.0\" \"2.2\" implements {\n  resources = [\"google_storage_bucket.audit\"]\n  interpretation = \"All entries land in the bucket.\"\n  duty_lock = \"Lock the bucket after validation.\"\n}\n";
        let file = satz::parse(src).unwrap();
        let rel = Path::new("monitoring/x.satz");
        let h = header(src, rel).unwrap();
        let cats = catalog("catalog: cis-gcp\nversion: \"4.0\"\ncontrols:\n  \"2.2\":\n    title: \"Sinks for all log entries\"\n    paraphrase: \"Every log entry reaches a sink.\"\n");
        let hist = [Change { version: "1.3".into(), date: "2026-09-04".into(), change: "the bucket".into() }];
        let existing = format!("old\n{}\nKeep me.\n{}\n", NOTES_START, NOTES_END);
        let md = render(rel, &file, &h, Some(&existing), &cats, &hist, &Library::new()).unwrap();

        assert!(md.contains("# `docs_test` — version 1.3"), "{}", md);
        assert!(md.contains("Log sink and bucket for the audit trail.\nSecond line."), "{}", md);
        assert!(md.contains("## Use it") && md.contains("use \"presets/monitoring/x.satz\""), "{}", md);
        assert!(md.contains("  bucket_location = \"EU\""), "the use block shows the defaults:\n{}", md);
        assert!(md.contains("- `customer_shortname` — no pack in the library declares it"), "{}", md);
        assert!(md.contains("| `bucket_location` | `\"EU\"` |") && md.contains("| `names` | `[ \"a\", \"b\" ]` |"), "{}", md);
        assert!(md.contains("| `google_storage_bucket` | `audit` |"), "{}", md);
        assert!(
            md.contains("| cis-gcp 4.0 | 2.2 | Sinks for all log entries | implements | `google_storage_bucket.audit` | All entries land in the bucket. |"),
            "{}",
            md
        );
        assert!(md.contains("- **Sinks for all log entries** (cis-gcp 4.0 §2.2) — Every log entry reaches a sink."), "{}", md);
        assert!(md.contains("- `lock` (cis-gcp 4.0 §2.2) — Lock the bucket after validation."), "{}", md);
        assert!(md.contains("Every resource this pack contributes is a witness"), "{}", md);
        assert!(md.contains("| 1.3 | 2026-09-04 | the bucket |"), "{}", md);
        assert!(md.contains("Keep me."), "the notes region must survive regeneration:\n{}", md);
        assert!(!md.contains("Converted by"));
    }

    #[test]
    fn a_pack_header_states_the_use_line_it_cannot_be_given() {
        // a bare list with no claims: nothing in the file names the resource map
        let src = "// Group memberships for the S1 model.\n\npack bare version \"1.0\"\n\n\"group:admins@{customer_domain}\" { role = \"x\" }\n";
        let file = satz::parse(src).unwrap();
        let rel = Path::new("security-group-models/bare.satz");
        let h = header(src, rel).unwrap();
        let e = render(rel, &file, &h, None, &Catalogs::new(), &[], &Library::new()).unwrap_err().to_string();
        assert!(e.contains("nothing says how this pack is used"), "{}", e);

        // …and when the header states it, it is lifted out of the purpose
        let src = "// Group memberships for the S1 model.\n//\n//   google_organization_iam_member { use \"presets/security-group-models/bare.satz\" }\n\npack bare version \"1.0\"\n\n\"group:admins@{customer_domain}\" { role = \"x\" }\n";
        let file = satz::parse(src).unwrap();
        let h = header(src, rel).unwrap();
        let md = render(rel, &file, &h, None, &Catalogs::new(), &[], &Library::new()).unwrap();
        let (purpose, rest) = md.split_once("## Use it").unwrap();
        assert!(rest.contains("google_organization_iam_member { use \"presets/security-group-models/bare.satz\" }"), "{}", md);
        assert!(!purpose.contains("use \"presets/"), "the lifted line must leave the purpose:\n{}", purpose);
    }

    #[test]
    fn a_header_summary_must_be_a_sentence() {
        let rel = Path::new("p.satz");
        let long = "x".repeat(SUMMARY_MAX + 1);
        for (src, want) in [
            ("pack p version \"1.0\"\n", "no header comment"),
            ("// https://example.com/benchmark\n\npack p version \"1.0\"\n", "bare URL"),
            ("// Include under cloud_identity_group:\n\npack p version \"1.0\"\n", "include instruction"),
            (&format!("// {}\n\npack p version \"1.0\"\n", long), "characters"),
        ] {
            let h = header(src, rel).unwrap();
            let e = summary(&h, rel).unwrap_err().to_string();
            assert!(e.contains(want), "expected {:?} in {:?}", want, e);
        }
        let h = header("// Budget for the infrastructure account. It alerts at 50%.\n\npack p version \"1.0\"\n", rel).unwrap();
        assert_eq!(summary(&h, rel).unwrap(), "Budget for the infrastructure account.");
    }

    #[test]
    fn an_unclaimed_resource_is_reported_and_a_reset_twin_says_so() {
        let src = "// Policies.\n\npack p version \"1.0\"\n\ngoogle_org_policy_policy {\n  live { spec { rules { enforce = \"TRUE\" } } }\n  \"legacy-twin\" { spec { reset = true } }\n  orphan { spec { rules { enforce = \"TRUE\" } } }\n}\n\nclaim \"cis-gcp\" \"4.0\" \"2.2\" implements { resources = [\"google_org_policy_policy.live\"] }\n";
        let file = satz::parse(src).unwrap();
        let rel = Path::new("p.satz");
        let h = header(src, rel).unwrap();
        let cats = catalog("catalog: cis-gcp\nversion: \"4.0\"\ncontrols:\n  \"2.2\":\n    title: \"t\"\n");
        let md = render(rel, &file, &h, None, &cats, &[], &Library::new()).unwrap();
        assert!(md.contains("`legacy-twin` *(off)*"), "the contributes table marks it:\n{}", md);
        assert!(md.contains("`google_org_policy_policy.legacy_twin` — declared OFF"), "{}", md);
        assert!(md.contains("`google_org_policy_policy.orphan` — contributed, but no claim names it."), "{}", md);
        assert!(!md.contains("google_org_policy_policy.live` — "), "a witnessed resource is not listed:\n{}", md);
    }

    #[test]
    fn the_changelog_table_is_parsed_and_a_missing_row_is_an_error() {
        let dir = std::env::temp_dir().join(format!("satz-changelog-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("p.satz"), "// A pack.\n\npack p version \"1.1\"\n").unwrap();
        let readme = |rows: &str| format!("# satz library\n\nprose\n\n## Changelog\n\n| pack | version | date | change |\n|---|---|---|---|\n{}", rows);

        std::fs::write(dir.join("README.md"), readme("| `p` | 1.1 | 2026-09-04 | first |\n")).unwrap();
        let all = packs(&dir).unwrap();
        let hist = changelog(&dir, &all).unwrap();
        assert_eq!(hist["p"].len(), 1);
        assert_eq!(hist["p"][0].date, "2026-09-04");

        std::fs::write(dir.join("README.md"), readme("| `p` | 1.0 | 2026-09-04 | first |\n")).unwrap();
        let e = changelog(&dir, &all).unwrap_err().to_string();
        assert!(e.contains("`p` 1.1 has no changelog row"), "{}", e);

        std::fs::write(dir.join("README.md"), readme("| `q` | 1.1 | 2026-09-04 | first |\n")).unwrap();
        let e = changelog(&dir, &all).unwrap_err().to_string();
        assert!(e.contains("not a pack in the library"), "{}", e);

        std::fs::write(dir.join("README.md"), "# satz library\n\nno section\n").unwrap();
        assert!(changelog(&dir, &all).unwrap_err().to_string().contains("no `## Changelog` section"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn the_shipped_library_renders_and_is_current() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        run(&root.join("presets"), &root.join("presets/docs"), true).expect("presets/docs is behind the packs — run `satz doc-packs` and commit");
    }

    #[test]
    fn a_claim_on_an_unknown_control_is_reported() {
        // The gate that was missing when the CIS 4.0 alert claims drifted one
        // id off the benchmark: a claim on a control the catalog does not know
        // proves nothing and must not ship — on the write path as much as under
        // `--check`, since the page now prints the control's title.
        let dir = std::env::temp_dir().join(format!("satz-claimgate-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("catalogs")).unwrap();
        std::fs::write(
            dir.join("catalogs/cis-gcp-4.0.yaml"),
            "catalog: cis-gcp\nversion: \"4.0\"\ncontrols:\n  \"2.4\":\n    title: \"x\"\n",
        )
        .unwrap();
        std::fs::write(
            dir.join("p.satz"),
            "pack p version \"1.0\"\n\nclaim \"cis-gcp\" \"4.0\" \"2.4\" implements { resources = [\"a.b\"] }\nclaim \"cis-gcp\" \"4.0\" \"2.99\" implements { resources = [\"a.b\"] }\n",
        )
        .unwrap();
        let all = packs(&dir).unwrap();
        let e = catalogs(&dir, &all).unwrap_err().to_string();
        assert!(e.contains("§2.99") && e.contains("1 claim(s)"), "{}", e);
        // a framework with no catalog file is an error, not a pass
        std::fs::write(dir.join("q.satz"), "pack q version \"1.0\"\n\nclaim \"nist\" \"800-53\" \"AC-1\" implements { resources = [\"a.b\"] }\n").unwrap();
        let all = packs(&dir).unwrap();
        assert!(catalogs(&dir, &all).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }
}
