//! A project on satz, end to end. An entry of `projects` in
//! `presets/project-onboarding.satz` gives the central estate the project's Google project,
//! IaC service account and state bucket, and the `interface "<name>"` that publishes them;
//! the pull request that adds the entry is the request's review. `satz init --project`
//! writes the project's own estate from that interface file.

use satz_core::satz::InterfaceFile;

/// The exports `presets/project-onboarding.satz` publishes and `init --project` reads, by name.
const PROJECT_ID: &str = "project_id";
const IAC_ACCOUNT: &str = "iac_account";
const STATE_BUCKET: &str = "state_bucket";
const REGION: &str = "default_region";

/// A project's name is an interface name and a folder name: `[a-z][a-z0-9-]*`, and not
/// the two folders `interfaces/` reserves.
pub(crate) fn valid_name(name: &str) -> Result<(), String> {
    let ok = name.chars().next().is_some_and(|c| c.is_ascii_lowercase())
        && name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-');
    if !ok {
        return Err(format!("`{}`: a project's name is an interface name — lowercase letters, digits and `-`, starting with a letter", name));
    }
    if name == satz_core::satz::CORE_INTERFACE || name == satz_core::satz::COMMON_LIBRARY {
        return Err(format!("`{}` is reserved: interfaces/{}/ is satz's", name, name));
    }
    Ok(())
}

/// The name as a Satz label and estate name.
pub(crate) fn label(name: &str) -> String {
    name.replace('-', "_")
}

/// A static string output of the interface, by name.
fn static_output(file: &InterfaceFile, name: &str) -> Option<String> {
    file.outputs.iter().find(|o| o.name == name).and_then(|o| crate::interface::static_text(&o.value))
}

/// The project's own estate, from the interface `presets/project-onboarding.satz` published
/// for it: it runs as the project's IaC service account, keeps its state in the project's
/// bucket, and reads the central estate through `use_path`. Refused when the interface lacks
/// one of the four exports the pack publishes.
pub(crate) fn estate(name: &str, file: &InterfaceFile, use_path: &str) -> Result<String, String> {
    valid_name(name)?;
    let read = |export: &str| -> Result<String, String> {
        static_output(file, export).ok_or_else(|| {
            let writer = if export == REGION {
                "`presets/estate-core.satz` exports it: switch its `use` line on in the central estate".to_string()
            } else {
                format!("an entry `{{ name = \"{}\" … }}` in `projects` of `presets/project-onboarding.satz` publishes it", name)
            };
            format!(
                "the interface `{}` of the estate `{}` publishes no static `{}` — {}; it publishes: {}",
                file.name,
                file.estate,
                export,
                writer,
                file.outputs.iter().map(|o| format!("`{}`", o.name)).collect::<Vec<_>>().join(", ")
            )
        })
    };
    let project_id = read(PROJECT_ID)?;
    let account = read(IAC_ACCOUNT)?;
    let bucket = read(STATE_BUCKET)?;
    let region = read(REGION)?;
    let account_id = account.split('@').next().unwrap_or(&account).to_string();
    const TEXT: &str = r#"// Generated by `satz init --project` — the estate of the project `@NAME@`: it reads the
// central estate `@CENTRAL@` through the interface file below and runs as the project's
// own IaC service account. Every value below is a param: change it here.

estate @LABEL@

params {
  infra_project_name = "@PROJECT@" // the project this estate runs in, and keeps its state in
  infra_bucket_name  = "@BUCKET@"
  svc_iac_account    = "@ACCOUNT@"
  default_region     = "@REGION@"
  default_zone       = "@REGION@-a"
  deployment_engine  = "tofu"
  deployment_mode    = "cloud"
}

// The central estate's interface: a value is read as `${{interface.<export>}}`; the
// README beside the file lists the values and what may be attached to, and `CHANGES.md`
// there, after a change of the central estate, what to do about it.
use "@USE@"

terraform {
  backend {
    local { path = "terraform.tfstate" }
    gcs {
      bucket = infra_bucket_name
      prefix = "hcl/state"
    }
  }
}

providers {
  "google" {
    project               = infra_project_name
    region                = default_region
    alias                 = "google"
    user_project_override = true
    billing_project       = infra_project_name
  }
  "google-beta" {
    project               = infra_project_name
    region                = default_region
    alias                 = "google-beta"
    user_project_override = true
    billing_project       = infra_project_name
  }
}

// The project's own resources, in its Google project: `project = "${{interface.project_id}}"`.
"#;
    Ok(TEXT
        .replace("@NAME@", name)
        .replace("@LABEL@", &label(name))
        .replace("@CENTRAL@", &file.estate)
        .replace("@PROJECT@", &project_id)
        .replace("@BUCKET@", &bucket)
        .replace("@ACCOUNT@", &account_id)
        .replace("@REGION@", &region)
        .replace("@USE@", use_path))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// The central estate `init` writes, with or without a workload folder, with the pack
    /// used and `projects` bound. `tag` keeps two tests' scratch directories apart: the
    /// runner interleaves them.
    fn central(tag: &str, folder: Option<&str>, projects: &str) -> String {
        let dir = std::env::temp_dir().join(format!("satz-project-{}-{}-{}", std::process::id(), tag, folder.is_some()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("C0example.satz");
        let mut args = crate::template::tests::args("first.admin", "example.com");
        args.workload_folder_name = folder.map(str::to_string);
        crate::template::generate_template(&args, None, &path).unwrap();
        let src = std::fs::read_to_string(&path).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        let parent = if folder.is_some() { "  project_onboarding_folder = \"google_folder.workload_folder.name\"\n" } else { "" };
        let src = src.replacen("params {\n", &format!("params {{\n  projects = [{}]\n{}", projects, parent), 1);
        format!("{}\nuse \"presets/project-onboarding.satz\"\n", src)
    }

    /// The library's pack from the repository, every other path refused.
    fn presets(p: &str) -> Result<String, String> {
        match p {
            "presets/project-onboarding.satz" => std::fs::read_to_string(p).map_err(|e| e.to_string()),
            other => Err(format!("no {}", other)),
        }
    }

    fn compile(src: &str, loader: &dyn Fn(&str) -> Result<String, String>) -> (crate::manifest::Manifest, crate::interface::Interface) {
        let reg = crate::corpus::registry();
        let resolver = crate::EstateResolver { registry: &reg };
        let fe = satz_core::pipeline::compile_estate("e.satz", src, &resolver, loader).unwrap_or_else(|e| panic!("front-end: {}\n{}", e, src));
        let folded = satz_core::pipeline::fold_fragments(&resolver, &fe.fragments);
        assert!(folded.conflicts().is_empty(), "{:?}", folded.conflicts());
        let mut ctx = crate::emitter::EmitCtx::from_env(&fe.env);
        ctx.registry = Some(&reg);
        let out = crate::emitter::emit(&folded, &ctx).unwrap();
        let i = crate::interface::build("e", &fe.exports, &fe.interfaces, &out.manifest, "hashicorp/google", None)
            .unwrap_or_else(|r| panic!("an export refused: {:?}", r));
        (out.manifest, i)
    }

    const PROJECTS: &str = "{ name = \"payments\" owner_group = \"payments-owners@example.com\" }, { name = \"data-lake\" owner_group = \"lake-owners@example.com\" }";

    /// An owner group that is no address, and a name that is no interface name, are
    /// refused at compile — naming the entry and the value — rather than at apply.
    #[test]
    fn a_malformed_entry_is_refused_at_compile() {
        let reg = crate::corpus::registry();
        let resolver = crate::EstateResolver { registry: &reg };
        for (entry, says) in [
            ("{ name = \"payments\" owner_group = \"payments-owners\" }", "entry `payments` has `owner_group` = \"payments-owners\""),
            ("{ name = \"payments\" owner_group = \"group:payments-owners@example.com\" }", "entry `payments` has `owner_group` = \"group:payments-owners@example.com\""),
            ("{ name = \"payments\" owner_group = \"payments-owners@example.com \" }", "entry `payments` has `owner_group`"),
            ("{ name = \"Payments\" owner_group = \"payments-owners@example.com\" }", "\"Payments\""),
        ] {
            let src = central(&format!("bad-{}", says.len()), None, entry);
            let e = satz_core::pipeline::compile_estate("e.satz", &src, &resolver, &presets).err().unwrap_or_else(|| panic!("{} compiled", entry));
            assert!(e.msg.contains(says), "{}: {}", entry, e.msg);
        }
    }

    /// One entry is one project: its Google project under the organisation or the workload
    /// folder, its grants, and its own interface — not a common one, though a pack writes
    /// it — with the four exports the project's estate is written from. A name with `-` is
    /// the label with `_`, in the resources and in the references the interface reads.
    #[test]
    fn each_entry_is_a_project_with_its_own_interface() {
        for folder in [None, Some("Workloads")] {
            let (manifest, i) = compile(&central("pack", folder, PROJECTS), &presets);
            let project = manifest.resources.values().find(|r| r.address() == "google_project.data_lake").expect("the project");
            match folder {
                None => assert_eq!(project.attrs.get("org_id").map(String::as_str), Some("123456789012"), "{:?}", project.attrs),
                Some(_) => assert_eq!(project.refs.get("folder_id").map(String::as_str), Some("google_folder.workload_folder.name"), "{:?}", project.refs),
            }
            for name in ["payments", "data-lake"] {
                assert!(i.projects().contains(&name.to_string()), "{} — {:?}", name, i.projects());
                let outputs: Vec<(&str, bool)> = i.module_outputs(name).iter().map(|o| (o.name.as_str(), o.static_text().is_some())).collect();
                for (export, is_static) in [("project_id", true), ("project_number", false), ("iac_account", true), ("state_bucket", true)] {
                    assert!(outputs.contains(&(export, is_static)), "{}: {} static={} — {:?}", name, export, is_static, outputs);
                }
            }
            assert_eq!(i.module_outputs("payments").into_iter().find(|o| o.name == "project_id").unwrap().attach, ["google_project_iam_member"]);
            assert_eq!(
                i.module_outputs("data-lake").into_iter().find(|o| o.name == "iac_account").unwrap().static_text().as_deref(),
                Some("svc-iac-data-lake@acme-data-lake-001.iam.gserviceaccount.com")
            );
            assert!(!i.module_outputs("payments").iter().any(|o| o.name == "state_bucket" && o.static_text().as_deref() == Some("acme-data-lake-001-state")), "one project's interface carries another's values");
            assert!(manifest.resources.values().any(|r| r.tf_type == "google_project_iam_member" && r.attrs.get("role").map(String::as_str) == Some("roles/resourcemanager.projectIamAdmin")));
            assert!(manifest.resources.values().any(|r| r.tf_type == "google_storage_bucket_iam_member" && r.attrs.get("bucket").map(String::as_str) == Some("acme-payments-001-state")));
            assert!(manifest.resources.values().any(|r| r.tf_type == "google_service_account_iam_member" && r.attrs.get("member").map(String::as_str) == Some("group:lake-owners@example.com")));
        }
        // no entry, no project and no interface
        let (manifest, i) = compile(&central("none", None, ""), &presets);
        assert!(!manifest.resources.values().any(|r| r.address() == "google_project.payments"));
        assert!(i.projects().is_empty(), "{:?}", i.projects());
    }

    /// `init --project` writes an estate from the four exports, in the canonical layout,
    /// that compiles as the project's own IaC service account.
    #[test]
    fn the_project_estate_runs_as_the_projects_account_and_reads_the_interface() {
        // the interface the central estate published, as the file a project takes; the
        // region is estate-core's export, which the estate `init` writes switches on later
        let src = format!("{}\nexport \"default_region\" = default_region\n", central("estate", None, PROJECTS));
        let (manifest, i) = compile(&src, &presets);
        let facts = crate::consumer::Facts::of_estate("e", Some(&i), &manifest);
        let text = satz_core::fmt::format(&i.satz_file("payments", &facts, "0.0.0", "e.satz")).unwrap();
        let file = satz_core::satz::parse(&text).unwrap().interface_file.unwrap();
        let estate = estate("payments", &file, "vendor/payments/payments/satz/interface.satz").unwrap();
        assert_eq!(satz_core::fmt::format(&estate).unwrap(), estate, "the project estate is not in the canonical layout");
        assert!(estate.contains("estate payments\n") && estate.contains("svc_iac_account    = \"svc-iac-payments\"") && estate.contains("infra_bucket_name  = \"acme-payments-001-state\""), "{}", estate);
        // compiled through the tail: cloud mode impersonates the project's account
        let reg = crate::corpus::registry();
        let resolver = crate::EstateResolver { registry: &reg };
        let fe = satz_core::pipeline::compile_estate("payments.satz", &estate, &resolver, &|p| if p.ends_with("interface.satz") { Ok(text.clone()) } else { Err(format!("no {}", p)) }).unwrap();
        let cfg = crate::parse_tool_config(Path::new("/nonexistent/config.toml")).unwrap();
        let graph = crate::pack_graph::Shipped::Missing(std::path::PathBuf::from("presets/pack-graph.json"));
        let t = crate::compile_tail(&fe, &resolver, &reg, &cfg, &graph, "presets", "warn", Path::new("payments.satz"), "payments.satz", &estate);
        let errors: Vec<&str> = t.findings.iter().filter(|f| f.severity == crate::findings::Severity::Error).map(|f| f.message.as_str()).collect();
        assert!(errors.is_empty(), "{:?}", errors);
        let providers = t.providers_tf.expect("providers.tf");
        assert!(providers.contains("impersonate_service_account = \"svc-iac-payments@acme-payments-001.iam.gserviceaccount.com\""), "{}", providers);
        // an interface without the exports is refused by name
        let bare = satz_core::satz::parse("interface \"x\"\n\ncentral {\n  estate = \"e\"\n  organizations = []\n}\n\noutput \"project_id\" {\n  value = \"p\"\n}\n").unwrap().interface_file.unwrap();
        let err = super::estate("payments", &bare, "x").unwrap_err();
        assert!(err.contains("publishes no static `iac_account`") && err.contains("`project_id`") && err.contains("project-onboarding.satz"), "{}", err);
        let no_region = satz_core::satz::parse(&text.replace("output \"default_region\"", "output \"region_gone\"")).unwrap().interface_file.unwrap();
        assert!(super::estate("payments", &no_region, "x").unwrap_err().contains("estate-core"));
    }
}
