//! The estate `satz init --customer-id` writes: the Day-0 skeleton `bootstrap`
//! expects (its imports are addressed by label — `google_folder.infra_folder`,
//! `google_project.infra`, `google_storage_bucket.state` — so those labels are
//! a contract, not a style). Written in Satz: a new customer's first file must
//! be one every command accepts.

use std::fs;
use std::path::Path;

pub struct TemplateArgs {
    pub customer_id: String,
    pub shortname: String,
    pub billing_id: String,
    pub region: String,
    pub org_id: String,
    pub domain: String,
    pub project_id: String,
    pub bucket_id: String,
    /// Local part of the initial admin address. The template and the shipped presets
    /// both compose members as `user:{first_admin}@{customer_domain}`, so this must not
    /// carry the domain.
    pub first_admin: String,
}

/// The estate name: the customer id as a Satz identifier.
fn estate_name(customer_id: &str) -> String {
    let mut s: String = customer_id
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

pub fn generate_template(args: &TemplateArgs, output_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let content = format!(
        r#"// Generated by `satz init` — the Day-0 estate `satz bootstrap` builds on.
// Every value below is a param: change it here, never in a pack.

estate {estate}

params {{
  infra_folder_name        = "Infrastructure"
  infra_project_name       = "{project_id}"
  infra_bucket_name        = "{bucket_id}"
  customer_id              = "{customer_id}"
  customer_organization_id = "{org_id}"
  customer_domain          = "{domain}"
  first_admin              = "{first_admin}"
  customer_longname        = ""
  customer_shortname       = "{shortname}"
  svc_iac_account          = "svc-iac-001"
  svc_iac_users_group      = "svc-iac-users"
  billing_account_infra    = "{billing_id}"
  deployment_engine        = "tofu"
  deployment_mode          = "local" // switched by `satz migrate`
  default_region           = "{region}"
  default_zone             = "{region}-a"
}}

terraform {{
  backend {{
    local {{ path = "terraform.tfstate" }}
    gcs {{
      bucket = infra_bucket_name
      prefix = "hcl/state"
    }}
  }}
}}

providers {{
  "google" {{
    project               = infra_project_name
    region                = default_region
    alias                 = "google"
    user_project_override = true
    billing_project       = infra_project_name
  }}
  "google-beta" {{
    project               = infra_project_name
    region                = default_region
    alias                 = "google-beta"
    user_project_override = true
    billing_project       = infra_project_name
  }}
}}

google_cloud_identity_group {{
  svc_iac_users {{
    id           = "{{svc_iac_users_group}}@{{customer_domain}}"
    display_name = "Service Account IaC Users"
    description  = "Service account users allowed to impersonate the IaC service account"
    owner        = [ "{{svc_iac_account}}@{{infra_project_name}}.iam.gserviceaccount.com" ]
    member       = [ "user:{{first_admin}}@{{customer_domain}}" ]
  }}
}}

google_organization_iam_member {{
  // the service account needs the Groups Admin role in the Workspace console as well
  "serviceAccount:{{svc_iac_account}}@{{infra_project_name}}.iam.gserviceaccount.com" = [
    "roles/billing.user",
    "roles/billing.projectManager",
    "roles/iam.organizationRoleAdmin",
    "roles/orgpolicy.policyAdmin",
    "roles/owner",
    "roles/resourcemanager.folderAdmin",
    "roles/resourcemanager.organizationAdmin",
    "roles/resourcemanager.projectIamAdmin",
    "roles/resourcemanager.projectCreator",
    "roles/iam.serviceAccountAdmin",
    "roles/serviceusage.serviceUsageAdmin",
    "roles/serviceusage.serviceUsageConsumer",
  ]
  "group:{{svc_iac_users_group}}@{{customer_domain}}" = [
    "roles/iam.serviceAccountTokenCreator",
    "roles/iam.serviceAccountUser",
    "roles/serviceusage.serviceUsageConsumer",
  ]
}}

google_billing_account_iam_member {{
  billing_account_id = billing_account_infra
  "serviceAccount:{{svc_iac_account}}@{{infra_project_name}}.iam.gserviceaccount.com" = [
    "roles/billing.admin",
  ]
}}

google_folder {{
  infra_folder {{
    display_name = infra_folder_name
    google_project {{
      infra {{
        project_id      = infra_project_name
        billing_account = billing_account_infra
        project_service = [
          "cloudasset.googleapis.com",
          "cloudbilling.googleapis.com",
          "cloudidentity.googleapis.com",
          "cloudresourcemanager.googleapis.com",
          "iam.googleapis.com",
          "iamcredentials.googleapis.com",
          "logging.googleapis.com",
          "orgpolicy.googleapis.com",
          "securitycenter.googleapis.com",
          "serviceusage.googleapis.com",
          "essentialcontacts.googleapis.com",
        ]
        google_storage_bucket {{
          state {{
            "import-id"                 = infra_bucket_name
            name                        = infra_bucket_name
            location                    = default_region
            force_destroy               = true
            public_access_prevention    = "enforced"
            uniform_bucket_level_access = true
            lifecycle_rule = [
              {{ action {{ type = "Delete" }}
                condition {{ num_newer_versions = 100 with_state = "ARCHIVED" }} }},
              {{ action {{ type = "Delete" }}
                condition {{ days_since_noncurrent_time = 365 }} }},
            ]
          }}
        }}
        google_service_account {{
          provisioner {{
            account_id   = svc_iac_account
            display_name = "Primary IaC Provisioner"
          }}
        }}
      }}
    }}
  }}
}}
"#,
        estate = estate_name(&args.customer_id),
        customer_id = args.customer_id,
        project_id = args.project_id,
        bucket_id = args.bucket_id,
        org_id = args.org_id,
        domain = args.domain,
        first_admin = args.first_admin,
        shortname = args.shortname,
        billing_id = args.billing_id,
        region = args.region,
    );

    fs::write(output_path, content)?;
    Ok(())
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::path::PathBuf;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("satz-tpl-{}-{}", std::process::id(), name));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create scratch dir");
        dir
    }

    pub(crate) fn args(first_admin: &str, domain: &str) -> TemplateArgs {
        TemplateArgs {
            customer_id: "C0example".into(),
            shortname: "acme".into(),
            billing_id: "012345-6789AB-CDEF01".into(),
            region: "europe-west3".into(),
            org_id: "123456789012".into(),
            domain: domain.into(),
            project_id: "acme-iac-infra".into(),
            bucket_id: "acme-iac-infra".into(),
            first_admin: first_admin.into(),
        }
    }

    #[test]
    fn members_are_composed_from_params_not_written_verbatim() {
        // Changing `first_admin` or `customer_domain` must update every reference;
        // the old YAML template once wrote the full address and silently diverged.
        let dir = scratch("params");
        let path = dir.join("out.satz");
        generate_template(&args("first.admin", "example.com"), &path).unwrap();
        let out = std::fs::read_to_string(&path).unwrap();
        assert!(out.contains(r#"member       = [ "user:{first_admin}@{customer_domain}" ]"#), "{out}");
        assert!(!out.contains("first.admin@example.com"), "{out}");
        assert!(out.contains(r#"first_admin              = "first.admin""#), "{out}");
        assert!(out.contains(r#"customer_domain          = "example.com""#), "{out}");
        assert!(out.contains("estate c0example"), "{out}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn estate_names_are_identifiers() {
        assert_eq!(estate_name("C0example"), "c0example");
        assert_eq!(estate_name("0abc-x"), "_0abc_x");
    }
}
